title: Personal Progress Blog
description: "Tracking Professional and Educational Progress"
author:
  name: "Morgan Montgomery"
  email: "morgan.montgomery95@gmail.com"
  url: "https://mmontgomery95.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Morgan Montgomery"
year : "2020"
